---
- name: Setup Vprofile bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws

  tasks:
    - name: Import VPC setup variable
      include_vars:
        file: vars/vpc_setup

    - name: Import output variables
      include_vars:
        file: vars/output_vars

    - name: Create EC2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out

    - name: Save private key into file
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: '0600'
      when: key_out.changed

    - name: Create security group for bastion host
      amazon.aws.ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from my IP
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    
    # - name: Create Bastion host EC2 instance
    #   amazon.aws.ec2_instance:
    #     key_name: vprofile-key
    #     region: "{{ region }}"
    #     instance_type: t2.micro
    #     image_id: "{{ bastion_ami }}"
    #     wait: yes
    #     wait_timeout: 300
    #     instance_tags:
    #       Name: Bastion_host
    #       Project: Vprofile
    #       Owner: DevOps Team
    #     exact_count: 1
    #     count_tag:
    #       Name: Bastion_host
    #       Project: Vprofile
    #       Owner: DevOps Team
    #     security_group_ids:
    #       - "{{ BastionSG_out.group_id }}"
    #     vpc_subnet_id: "{{ pubsub1id }}"
    #   register: bastionHost_out

